development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: adamweeks
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: adamweeks
  password: